{{- if not .Values.passboltEnv.secretName }}
{{- $type := "sec" -}}
{{- $action := "env" -}}
{{- $Name := include "passbolt-library.fullname" . -}}
{{- $fullName := printf "%s-%s-%s" $Name $type $action -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "passbolt-library.labels" . | nindent 4 }}
    {{- include "passbolt-library.selectorLabels" . | nindent 4 }}
    {{- include "passbolt-library.typelabels" (dict "action" $action "type" $type) | nindent 4 }}
type: Opaque
data:
{{ include "passbolt-library.secret-range.tpl" .Values.passboltEnv.secret | nindent 2 }}
{{- if eq .Values.app.database.kind "postgresql" }}
    {{- $username := .Values.passboltEnv.secret.DATASOURCES_DEFAULT_USERNAME }}
    {{- $password := .Values.passboltEnv.secret.DATASOURCES_DEFAULT_PASSWORD }}
    {{- $database := .Values.passboltEnv.secret.DATASOURCES_DEFAULT_DATABASE }}
    {{- $schema := ( default "passbolt" .Values.passboltEnv.secret.DATASOURCES_DEFAULT_SCHEMA ) }}
    {{- $host := ( include "passbolt.databaseServiceName" . ) | replace "\"" "" }}
    {{- $port := ( default "5432" .Values.passboltEnv.plain.DATASOURCES_DEFAULT_PORT) | toString }}
    DATASOURCES_DEFAULT_URL: {{ printf "postgres://%s:%s@%s:%s/%s?schema=%s" $username $password $host $port $database $schema | toString | b64enc }}
{{- end -}}
{{- end }}